import { IDaoDetail, IProposalsItem } from './type';
export const mokeData: IDaoDetail = {
  chainId: '',
  daoId: '',
  metadata: {
    name: 'Network DAO',
    logoUrl: '',
    description:
      'AELF is a fully decentralized community governed protocol by the ELF token-holders. ELF token-holders collectively discuss, propose, and vote on upgrades to the protocol. ELF token-holders (aelf netwotk only) can either vote themselves on new proposals or delegate to an address of choice. To learn more, check out the Governance documentation.',
    socialMedia: {
      twitter: '',
      facebook: '',
      discrod: '',
      telegram: '',
      reddit: '',
    },
  },
  creator: 'ELF_2PeasdfasdfasfasdfW28l_tDVW',
  governanceToken: 'dfasdfa',
  network: 'sdfasd',
  governanceModel: 'fdsfasd',
  treasuryContractAddress: '',
  voteContractAddress: '',
  electionContractAddress: '',
  governanceContractAddress: '',
  timelockContractAddress: '',
  memberCount: 11,
  candidateCount: 22,
  // ELF_2Pew…W28l_tDVW
  fileInfoList: [
    {
      name: 'aaaa',
      cid: '11',
      url: '',
    },
  ],
};

export const list: IProposalsItem[] = [
  {
    chainId: '',
    proposalId: '2dfasdfasdfasdfasdfa',
    releaseAddress: '',
    deployTime: '',
    proposalTitle: '',
    governanceMechanism: 'parliament',
    proposalStatus: 'Active',
    proposalDescription: '',
    proposalType: '', //Governance / Advisory
    startTime: '',
    endTime: '',
    expiredTime: '',
    transaction: {
      contractMethodName: '',
      toAddress: '',
      params: {
        param1: 'value1',
        param2: 'value2',
      },
    },
    votesAmount: '1000',
    approvedCount: '',
    rejectionCount: '',
    abstentionCount: '',
    voterCount: 10,
    minimalRequiredThreshold: 20,
    minimalVoteThreshold: 10,
    minimalApproveThreshold: 10,
    maximalRejectionThreshold: 10,
    maximalAbstentionThreshold: 10,
    tagList: ['updateContract', 'governance'],
  },
  {
    chainId: '',
    proposalId: '3',
    releaseAddress: '',
    deployTime: '',
    proposalTitle: 'fsdasdfadfa',
    governanceMechanism: 'parliament',
    proposalStatus: 'Active',
    proposalDescription: '',
    proposalType: '', //Governance / Advisory
    startTime: '',
    endTime: '',
    expiredTime: '',
    transaction: {
      contractMethodName: '',
      toAddress: '',
      params: {
        param1: 'value1',
        param2: 'value2',
      },
    },
    votesAmount: '100',
    approvedCount: '',
    rejectionCount: '',
    abstentionCount: '',
    voterCount: 10,
    minimalRequiredThreshold: 20,
    minimalVoteThreshold: 10,
    minimalApproveThreshold: 10,
    maximalRejectionThreshold: 10,
    maximalAbstentionThreshold: 10,
    tagList: ['updateContract', 'governance'],
  },
];
